### ISSUE TITLE
0% A Rate for Spring 2022 Courses

### ISSUE THREAD

**Issue by jamesjulich** [Madgrades/madgrades-extractor#17]
Courses taught in Spring 2022 appear to have a 0.0% A rate, despite the grade report from the registrar saying otherwise.

For instance, MATH 340 taught by Peter Juhasz (Lec 002 and Lec 003) shows 0 As being granted for the Spring 2022 semester. The actual A rate should be ~30%.

Philosophy 101 taught by Henry Southgate in Spring 2022 is another class that is having the same issue.

These are just two classes that I have noticed that have the issue, but it is likely a much more widespread issue. I'm going to run this program on my system to figure out whether this was an issue with the extractor or an issue updating the databases. I'll update this issue thread if I find anything.

**Comment by jamesjulich** [comment]
^ After running the program on the most recent DIR and grade distribution report, it looks like the extracted grade distributions are inaccurate. I'm going to take a look at it. If I figure anything out, I'll update here/submit a PR.

**Comment by thekeenant** [comment]
Thanks for flagging! I just reverted the website back to Fall.

**Comment by jamesjulich** [comment]
Looks like the columns just need to be adjusted. The last decimal place of the GPA is clipping into the column of the A's column.

![IMG_19D065D2D036-1](https://user-images.githubusercontent.com/51384945/203695771-a3c7e941-c8d4-4858-91e9-d2f95bd15a97.jpeg)

**Comment by jamesjulich** [comment]
I went ahead and submitted a PR that fixes this issue. Let me know if you have questions or need anything.

**Comment by thekeenant** [comment]
Thanks for the help, it seems to be working with the fix but let me know if the data still seems wrong.
